version: "3.9"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  web:
    build: .
    stdin_open: true
    tty: true
    ports:
      - 8000:80
    links:
      - db:database
    volumes:
      - upload:/var/www/localhost/htdocs/basic/web/upload

volumes:
  db:
    driver: local
  upload:
    driver: local
